version: "3.8"
services:
  client:
    image: fc-retrieval-client:dev
    container_name: client
    ports:
      - "80:80"
      - "443:443"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
    networks:
      - shared
    depends_on: 
      - gateway
                
  gateway:
    image: fc-retrieval-gateway:dev
    container_name: gateway
    networks:
      - shared

  dbg:
   image: busybox
   #image: radial/busyboxplus:curl
   container_name: dbg
   stdin_open: true
   tty: true
   networks:
     - shared
     
networks:
  shared:
