version: "3.7"

services:
  gateway:
    container_name: fc-retrieval/gateway
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "9010:9010"
      - "9011:9011"
      - "9012:9012"
      - "9013:9013"
    volumes:
      - ./logs:${LOG_DIR}
      - ./:/go/src/app
      - ./go.local.mod:/go/src/app/go.mod
      - ../fc-retrieval/common:/go/src/fc-retrieval/common
      - ../fc-retrieval/register:/go/src/fc-retrieval/register
    env_file:
      - .env
    environment:
      - REGISTER_API_URL=http://register:9020
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    name: shared
    external: true
